Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/mathsat.py", line 152, in <lambda>
    __setattr__ = lambda self, name, value: _swig_setattr(self, msat_term, name, value)
  File "/usr/local/lib/python3.8/dist-packages/mathsat.py", line 71, in _swig_setattr
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)
  File "/usr/local/lib/python3.8/dist-packages/mathsat.py", line 56, in _swig_setattr_nondynamic
    self.__dict__[name] = value
KeyboardInterrupt

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/F3/src/run_f3.py", line 467, in <module>
    main(config_args().parse_args())
  File "/home/F3/src/run_f3.py", line 463, in main
    run_f3(bench, out_dir)
  File "/home/F3/src/run_f3.py", line 277, in run_f3
    res = solve_problem(prob, label, out_dir)
  File "/home/F3/src/run_f3.py", line 268, in solve_problem
    return run_ltl_test(problem, env, label, out_dir)
  File "/home/F3/src/run_f3.py", line 127, in run_ltl_test
    return search_nonterm(env, symbols, init, trans, fairness,
  File "/home/F3/src/run_f3.py", line 184, in search_nonterm
    _, arg0, arg1 = search_funnel_bmc(env, symbols, init, trans,
  File "/home/F3/src/main.py", line 260, in search_funnel_bmc
    is_rf, args = rf_or_funnel_from_trace(env, symbols, trace, abst_path,
  File "/home/F3/src/main.py", line 714, in rf_or_funnel_from_trace
    model = instantiate_funnel_template(nontermarg)
  File "/home/F3/src/main.py", line 786, in instantiate_funnel_template
    model = funnel_t.motzkin_instantiate(extra=learn if get_fun_learn_ef()
  File "/home/F3/src/funnel.py", line 680, in motzkin_instantiate
    solver.add_assertion(c)
  File "/home/F3/src/multisolver.py", line 160, in add_assertion
    s.add_assertion(formula, named=named)
  File "/usr/local/lib/python3.8/dist-packages/PySMT-0.9.1.dev332-py3.8.egg/pysmt/solvers/solver.py", line 342, in add_assertion
    tracked = self._add_assertion(formula, named=named)
  File "/usr/local/lib/python3.8/dist-packages/PySMT-0.9.1.dev332-py3.8.egg/pysmt/decorators.py", line 64, in clear_pending_pop_wrap
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/PySMT-0.9.1.dev332-py3.8.egg/pysmt/solvers/msat.py", line 219, in _add_assertion
    term = self.converter.convert(formula)
  File "/usr/local/lib/python3.8/dist-packages/PySMT-0.9.1.dev332-py3.8.egg/pysmt/decorators.py", line 84, in catch_conversion_error_wrap
    res = f(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/PySMT-0.9.1.dev332-py3.8.egg/pysmt/solvers/msat.py", line 773, in convert
    res = self.walk(rformula)
  File "/usr/local/lib/python3.8/dist-packages/PySMT-0.9.1.dev332-py3.8.egg/pysmt/walkers/dag.py", line 106, in walk
    res = self.iter_walk(formula, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/PySMT-0.9.1.dev332-py3.8.egg/pysmt/walkers/dag.py", line 98, in iter_walk
    self._process_stack(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/PySMT-0.9.1.dev332-py3.8.egg/pysmt/walkers/dag.py", line 91, in _process_stack
    self._compute_node_result(formula, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/PySMT-0.9.1.dev332-py3.8.egg/pysmt/walkers/dag.py", line 75, in _compute_node_result
    self.memoization[key] = f(formula, args=args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/PySMT-0.9.1.dev332-py3.8.egg/pysmt/solvers/msat.py", line 790, in walk_or
    res = mathsat.msat_make_or(self.msat_env(), res, a)
  File "/usr/local/lib/python3.8/dist-packages/mathsat.py", line 553, in msat_make_or
    return _mathsat.msat_make_or(e, t1, t2)
SystemError: <built-in function msat_make_or> returned a result with an error set
real 3602.97
user 0.00
sys 0.00
