ERROR:root:
Traceback (most recent call last):
  File "/home/anant/tool/build/t2parser.py", line 97, in nontermCheck
    t2lassoParser.main_func(lassoStr, extractInv)
  File "/home/anant/tool/build/t2lassoParser.py", line 579, in main_func
    parserAnant.main_func(f_name, extractInv)
  File "/home/anant/tool/build/parserAnant.py", line 339, in main_func
    out = parserConcrete.main_func(f_i_name)
  File "/home/anant/tool/build/parserConcrete.py", line 324, in main_func
    out = yacc.parse(f.read(), lexer=lexer)
  File "/home/anant/tool/ply/yacc.py", line 265, in parse
    return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
  File "/home/anant/tool/ply/yacc.py", line 971, in parseopt_notrack
    p.callable(pslice)
  File "/home/anant/tool/build/parserConcrete.py", line 95, in p_cycle_withComments
    line = "{} {} {} {}\n{} {} {}\n{}".format(*p[1:])
  File "/home/anant/tool/ply/yacc.py", line 198, in __getitem__
    if n >= 0: return self.slice[n].value
TypeError: '>=' not supported between instances of 'slice' and 'int'
real 41.99
user 40.98
sys 0.56
